version: "3"
services:
    web:
      tty: true
      build:
        context: .
        dockerfile: Dockerfile
      container_name: django_lot14
      ports:
        - "8010:8010"
      restart: always
      command: >
        sh -c "python3 manage.py makemigrations
               gunicorn --bind 0.0.0.0:8010 project.wsgi"
      environment:
        ALLOWED_HOST: "*"
        DEBUG: "1"
        DB_HOST: db
        DB_NAME: app
        DB_USER: postgres
        DB_PASSWORD: 12345
      depends_on:
        - db
    db:
      image: postgres:15-alpine
      environment:
        POSTGRES_DB: app
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345
      ports:
        - "5432:5432"
      volumes:
        - ./tmp_db/:/var/lib/postgresql/data
