# Generated by Django 4.1.7 on 2023-03-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_answer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.answer')),
                ('from_question_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_relations', to='questionnaire.question')),
                ('to_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relations', to='questionnaire.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire'),
        ),
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic_text', models.TextField()),
                ('questions_relation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionsrelation')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question'),
        ),
    ]
