# Generated by Django 4.1.7 on 2023-04-04 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_delete_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsrelation',
            name='questionnaire_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='questionnaire.questionnaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaire_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.questionnaire'),
        ),
    ]
