# Generated by Django 4.1.7 on 2023-04-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_questionsrelation_questionnaire_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionnaire_id',
            new_name='questionnaire',
        ),
        migrations.RenameField(
            model_name='questionsrelation',
            old_name='from_answer_id',
            new_name='from_answer',
        ),
        migrations.RenameField(
            model_name='questionsrelation',
            old_name='from_question_id',
            new_name='from_question',
        ),
        migrations.RenameField(
            model_name='questionsrelation',
            old_name='questionnaire_id',
            new_name='questionnaire',
        ),
        migrations.RenameField(
            model_name='questionsrelation',
            old_name='to_question_id',
            new_name='to_question',
        ),
    ]
